### ISSUE TITLE
Add a persistent context to save data between executions

### ISSUE THREAD

**Issue by jrmi** [mhcomm/pypeman#44]
We can save data in node class but they are lost if we restart pypeman. Some use cases for this feature:
- We want to periodically import data from database by filtering only entries modified since last import.
- We want to scan only new files since last channel launch.

I think we can imagine a lots of other use cases.

We can do it with a small database like pickle or shelve. Something simple as we are not going to put big things inside.

**Comment by feenes** [comment]
shelf is one option.
Another one could be to store the pickle values in an sqlite file as it is more robust against file corruption caused by crashes or power failures.

this can be done manually or by using the python module sqlitedict

**Comment by jrmi** [comment]
Yes, we NEED this fiability.
